# Generated by Django 3.2.13 on 2022-05-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_place_name', models.CharField(max_length=500)),
                ('review_pos_neg', models.IntegerField()),
                ('review_content', models.CharField(max_length=500)),
                ('review_writer', models.CharField(max_length=200)),
            ],
        ),
    ]
